import dotenv from 'dotenv';
dotenv.config();
import { createApp } from './app';
import { initializeFirebase } from './config/firebase';
import { createServer } from 'http';
import { setupWebsocket } from './websocket/server';
initializeFirebase();
const app = createApp();
const server = createServer(app);
setupWebsocket(server);
const PORT = Number(process.env.PORT || 3000);
server.listen(PORT, () => console.log(`✅ Server on http://localhost:${PORT}`));
export { app, server };
